# The following configuration is for integrating Swagger UI with Azure Active Directory
server:
  forward-headers-strategy: framework # This is required for redirection with HTTPS.
  port: 8080
springdoc:
  swagger-ui:
    use-root-path: true
    oauth:
      use-pkce-with-authorization-code-grant: true

spring:
  datasource:
    url: jdbc:sqlserver://sqlserver-complete-gridspertise.database.windows.net:1433;database=COMPLETE_STAGING_GRIDSPERTISE;encrypt=true
    username: ComplEtE-Staging
    password: C0mpl3t3St4g1ng!123!gridspertise
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate.default_schema: ComplEtE
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 4639bedb-2f9b-4af7-9bce-32d22d6c3de6
        credential:
          client-id: 851e58b8-f85e-4114-a4b0-00ee613878b7
        app-id-uri: api://851e58b8-f85e-4114-a4b0-00ee613878b7